### PR TITLE
Core System Enhancements

### PR DESCRIPTION
**Pull request by senhas-rgb**
Memory Management Enhancement
ACPI Support
Partially implements (System Information)

### CODE REVIEW

**Comment by senhas-rgb** [comment]
um you can remove edits to some files by seperate commits. Each file edits seperated into single commits for easier management of prs

**Review by kcirtap342 — COMMENTED** [review]
worst code on the planet ! i dont wanna see anything like this again ! (jk, still not merging though)

**Comment by senhas-rgb** [comment]
bruh

**Comment by senhas-rgb** [comment]
sed lyfe

**Pull request closed without merging**
